from . import gpu as gpu

GPU_ENABLED: bool
gpaw_cpp: bool
gpu_aware_mpi: bool
have_openmp: bool
libxc_version: str
version: int

from ._gpaw_manual import *
# mypy: disable-error-code=no-redef

"""Automatic, but rather unhelpful, stubs for _gpaw. These are functions
created with the raw CPython API without including any type info or
docstrings.
Commented out Operator and Spline which are types, not functions, in the
purepython version (suppresses mypy error).
"""
def FFTWDestroy(*args, **kwargs): ...
def FFTWExecute(*args, **kwargs): ...
def FFTWPlan(*args, **kwargs): ...
def GG_shuffle(*args, **kwargs): ...
def LFC(*args, **kwargs): ...
#def Operator(*args, **kwargs): ...
#def Spline(*args, **kwargs): ...
def Transformer(*args, **kwargs): ...
def WOperator(*args, **kwargs): ...
def XCFunctional(*args, **kwargs): ...
def add_linear_field_gpu(*args, **kwargs): ...
def add_to_density(*args, **kwargs): ...
def add_to_density_gpu(*args, **kwargs): ...
def adjust_momenta(*args, **kwargs): ...
def adjust_positions(*args, **kwargs): ...
def ax2py_gpu(*args, **kwargs): ...
def axpbyz_gpu(*args, **kwargs): ...
def axpbz_gpu(*args, **kwargs): ...
def axpy_gpu(*args, **kwargs): ...
def blacs_destroy(*args, **kwargs): ...
def calculate_forces_H2O(*args, **kwargs): ...
def calculate_residuals_gpu(*args, **kwargs): ...
def csign_gpu(*args, **kwargs): ...
def dH_aii_times_P_ani_gpu(*args, **kwargs): ...
def dotc_gpu(*args, **kwargs): ...
def dotu_gpu(*args, **kwargs): ...
def eed_region(*args, **kwargs): ...
def elementwise_multiply_add_gpu(*args, **kwargs): ...
def evaluate_lda_gpu(*args, **kwargs): ...
def evaluate_mpa_poly(*args, **kwargs): ...
def evaluate_pbe_gpu(*args, **kwargs): ...
def fd_precond(*args, **kwargs): ...
def fill_gpu(*args, **kwargs): ...
def flush_pending_decrefs(*args, **kwargs): ...
def gemm_gpu(*args, **kwargs): ...
def gemv_gpu(*args, **kwargs): ...
def get_blacs_gridinfo(*args, **kwargs): ...
def get_blacs_local_shape(*args, **kwargs): ...
def get_num_threads(*args, **kwargs): ...
def githash(*args, **kwargs): ...
def globally_broadcast_bytes(*args, **kwargs): ...
def gpaw_gpu_delete(*args, **kwargs): ...
def gpaw_gpu_init(*args, **kwargs): ...
def hartree(*args, **kwargs): ...
def integrate_inwards(*args, **kwargs): ...
def integrate_outwards(*args, **kwargs): ...
def localize(*args, **kwargs): ...
def lxcXCFuncNum(*args, **kwargs): ...
def lxcXCFunctional(*args, **kwargs): ...
def map_k_points(*args, **kwargs): ...
def mmm(*args, **kwargs): ...
def mmm_gpu(*args, **kwargs): ...
def multi_ax2py_gpu(*args, **kwargs): ...
def multi_axpy_gpu(*args, **kwargs): ...
def multi_dotc_gpu(*args, **kwargs): ...
def multi_dotu_gpu(*args, **kwargs): ...
def multi_elementwise_multiply_add_gpu(*args, **kwargs): ...
def multi_scal_gpu(*args, **kwargs): ...
def new_blacs_context(*args, **kwargs): ...
def pack(*args, **kwargs): ...
def pawexxvv(*args, **kwargs): ...
def pblas_gemm(*args, **kwargs): ...
def pblas_gemv(*args, **kwargs): ...
def pblas_hemm_symm(*args, **kwargs): ...
def pblas_r2k(*args, **kwargs): ...
def pblas_rk(*args, **kwargs): ...
def pblas_tran(*args, **kwargs): ...
def pc_potential(*args, **kwargs): ...
def plane_wave_grid(*args, **kwargs): ...
def pw_amend_insert_realwf_gpu(*args, **kwargs): ...
def pw_insert(*args, **kwargs): ...
def pw_insert_gpu(*args, **kwargs): ...
def pw_norm_gpu(*args, **kwargs): ...
def pw_norm_kinetic_gpu(*args, **kwargs): ...
def pw_precond(*args, **kwargs): ...
def pwlfc_expand(*args, **kwargs): ...
def pwlfc_expand_gpu(*args, **kwargs): ...
def pwlfc_expand_old(*args, **kwargs): ...
def r2k(*args, **kwargs): ...
def r2k_gpu(*args, **kwargs): ...
def rk(*args, **kwargs): ...
def rk_gpu(*args, **kwargs): ...
def scal_gpu(*args, **kwargs): ...
def scalapack_diagonalize_dc(*args, **kwargs): ...
def scalapack_diagonalize_ex(*args, **kwargs): ...
def scalapack_general_diagonalize_dc(*args, **kwargs): ...
def scalapack_general_diagonalize_ex(*args, **kwargs): ...
def scalapack_inverse(*args, **kwargs): ...
def scalapack_inverse_cholesky(*args, **kwargs): ...
def scalapack_redist(*args, **kwargs): ...
def scalapack_set(*args, **kwargs): ...
def scalapack_solve(*args, **kwargs): ...
def spherical_harmonics(*args, **kwargs): ...
def spline_to_grid(*args, **kwargs): ...
def symmetrize(*args, **kwargs): ...
def symmetrize_ft(*args, **kwargs): ...
def symmetrize_return_index(*args, **kwargs): ...
def symmetrize_wavefunction(*args, **kwargs): ...
def symmetrize_with_index(*args, **kwargs): ...
def tci_overlap(*args, **kwargs): ...
def tetrahedron_weight(*args, **kwargs): ...
def unpack(*args, **kwargs): ...
def unpack_complex(*args, **kwargs): ...
def utilities_gaussian_wave(*args, **kwargs): ...
def vdw(*args, **kwargs): ...
def vdw2(*args, **kwargs): ...
